// src/app/guides/how-to-become-filer-pakistan/page.jsx

import GuideLayout from '@/app/components/GuideLayout';
import Link from 'next/link';

export const metadata = {
  title: 'How to Become a Tax Filer in Pakistan (2026 Guide)',
  description:
    'Step-by-step guide to becoming an active tax filer in Pakistan. Learn how to file your FBR income tax return, appear on the ATL, and enjoy lower withholding tax rates.',
  alternates: {
    canonical: 'https://www.akbartaxstore.com/guides/how-to-become-filer-pakistan',
  },
  openGraph: {
    title: 'How to Become a Tax Filer in Pakistan (2026 Guide)',
    description:
      'Complete 2026 guide to becoming an FBR active filer. File your income tax return on IRIS, appear on ATL, and save thousands in withholding taxes.',
    url: 'https://www.akbartaxstore.com/guides/how-to-become-filer-pakistan',
  },
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Become a Tax Filer in Pakistan',
  description: 'Step-by-step process to file your FBR income tax return and appear on the Active Taxpayer List (ATL).',
  totalTime: 'PT45M',
  step: [
    { '@type': 'HowToStep', position: 1, name: 'Get Your NTN', text: 'Register on the FBR IRIS portal to obtain your NTN. For individuals, CNIC is the NTN — but you must activate it on IRIS.' },
    { '@type': 'HowToStep', position: 2, name: 'Gather Documents', text: 'Collect salary certificate, bank statements, asset details, and expense records for the relevant tax year.' },
    { '@type': 'HowToStep', position: 3, name: 'Log Into IRIS and Open Return Form', text: 'Log into iris.fbr.gov.pk. Go to Declaration > Income Tax Return and select the correct tax year.' },
    { '@type': 'HowToStep', position: 4, name: 'Fill Income and Wealth Details', text: 'Enter your salary/business income, bank account details, assets, liabilities, and any deductible expenses.' },
    { '@type': 'HowToStep', position: 5, name: 'Submit and Pay Any Tax Due', text: 'Review the return, submit it, and pay any tax balance using a PSID generated by IRIS via internet banking or ATM.' },
    { '@type': 'HowToStep', position: 6, name: 'Verify ATL Status', text: 'After filing, verify your ATL status by sending SMS "ATL [CNIC]" to 9966 or checking the FBR website. ATL typically updates within 24–72 hours.' },
  ],
};

const META = {
  title: 'How to Become a Tax Filer in Pakistan (2026 Guide)',
  h1: 'How to Become a Tax Filer in Pakistan — 2026 Complete Guide',
  intro:
    'Becoming an active tax filer in Pakistan means filing your FBR income tax return and appearing on the Active Taxpayer List (ATL). This guide covers every step, who qualifies, and how to avoid late-filer penalties.',
  category: 'Tax Filing',
  updatedDate: 'March 2026',
  readTime: '8',
};

const TOC = [
  { id: 'what-is-filer',       label: 'What is a Tax Filer?' },
  { id: 'who-must-file',       label: 'Who Must File a Return?' },
  { id: 'documents-needed',    label: 'Documents You Need' },
  { id: 'step-by-step',        label: 'Step-by-Step Filing Process' },
  { id: 'atl-surcharge',       label: 'Late Filing & ATL Surcharge' },
  { id: 'verify-atl',          label: 'How to Verify Your ATL Status' },
  { id: 'faq',                 label: 'Frequently Asked Questions' },
];

export default function BecomeFillerGuidePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
      />
      <GuideLayout meta={META} toc={TOC}>

        <h2 id="what-is-filer">What is a Tax Filer in Pakistan?</h2>
        <p>
          A <strong>tax filer</strong> is a person whose name appears on the FBR's <strong>Active Taxpayer List (ATL)</strong>. The ATL is updated daily by FBR and is publicly searchable. Being on this list means you have filed your income tax return for the current or previous tax year and are recognised as a compliant taxpayer by Pakistan's tax authority.
        </p>
        <p>
          There are three taxpayer categories under Pakistan's current tax framework:
        </p>
        <ul>
          <li><strong>Active Filer</strong> — Filed return by the deadline. Enjoys the lowest withholding tax rates on all transactions.</li>
          <li><strong>Late Filer</strong> — Filed return after the deadline. Still appears on ATL after paying the ATL surcharge, but faces higher withholding tax rates on property transactions (6% on sale under Section 236C, vs 3% for active filers).</li>
          <li><strong>Non-Filer</strong> — Has not filed a return. Faces the highest withholding tax rates and restrictions on financial activities.</li>
        </ul>
        <div className="callout">
          <strong>Key fact:</strong> Your ATL status is valid until September 30 of the following year. For example, if you file your 2024–25 return before the October 2025 deadline, your active filer status is maintained until September 30, 2026.
        </div>

        <h2 id="who-must-file">Who Must File an Income Tax Return in Pakistan?</h2>
        <p>You are legally required to file an income tax return if any of the following apply:</p>
        <ul>
          <li>Your monthly income exceeds <strong>PKR 50,000</strong> (PKR 600,000 annually)</li>
          <li>You own immovable property (land, house, apartment)</li>
          <li>You own a motor vehicle</li>
          <li>You have a bank balance or investments</li>
          <li>You want to reduce withholding tax deductions on banking, property, or vehicle transactions</li>
          <li>You intend to apply for a visa, loan, or government tender</li>
          <li>You are a company director or partner in a business</li>
        </ul>
        <p>
          Even if your income is below PKR 600,000, <strong>filing a nil return is strongly recommended</strong>. It costs nothing, takes under 30 minutes, and maintains your active filer status — protecting you from higher withholding taxes.
        </p>

        <h2 id="documents-needed">Documents You Need Before Filing</h2>

        <h3>For Salaried Individuals</h3>
        <ul>
          <li>Salary certificate or annual income tax statement from your employer</li>
          <li>CNIC (13-digit number)</li>
          <li>Bank account statements for the tax year (July 1 – June 30)</li>
          <li>Details of any other income (rental, freelance, investment)</li>
          <li>Details of assets owned (property address, vehicle registration)</li>
          <li>Details of any loans or liabilities</li>
        </ul>

        <h3>For Business Owners / Freelancers</h3>
        <ul>
          <li>Business income records and profit/loss summary</li>
          <li>Bank statements showing all business receipts and payments</li>
          <li>Tax deducted at source certificates (from clients or employers)</li>
          <li>Advance tax paid receipts (if any)</li>
          <li>Asset register (property, machinery, vehicles, stock)</li>
          <li>Liability register (bank loans, creditors)</li>
          <li>Foreign remittance certificates (for freelancers receiving payments from abroad)</li>
        </ul>
        <div className="callout-warning">
          <strong>Wealth reconciliation is critical.</strong> Your closing assets minus opening assets must match your declared income minus expenses. A mismatch triggers an FBR audit notice. If you have inherited property or received gifts, document these clearly before filing.
        </div>

        <h2 id="step-by-step">Step-by-Step Tax Return Filing on FBR IRIS</h2>

        <h3>Step 1 — Get Your NTN First</h3>
        <p>
          If you are filing for the first time, you must first <Link href="/guides/how-to-get-ntn-pakistan">register for an NTN on the IRIS portal</Link>. For individuals, your CNIC is your NTN — but it must be activated on IRIS before you can file a return.
        </p>

        <h3>Step 2 — Log Into IRIS</h3>
        <p>
          Visit <strong>iris.fbr.gov.pk</strong> and log in using your CNIC (or NTN for companies) and password. If you have forgotten your password, use the password reset option on the login page.
        </p>

        <h3>Step 3 — Open the Income Tax Return Form</h3>
        <p>
          On the IRIS dashboard, navigate to <strong>Declaration → Income Tax Return</strong>. Select the appropriate return type based on your income:
        </p>
        <ul>
          <li><strong>Form 114(1)</strong> — For salaried individuals</li>
          <li><strong>Form 114(2)</strong> — For business individuals and AOPs</li>
          <li><strong>Form 114(3)</strong> — For companies</li>
        </ul>
        <p>Select the correct <strong>Tax Year</strong>. For income earned between July 1, 2025 and June 30, 2026, select Tax Year 2026.</p>

        <h3>Step 4 — Fill Income Details</h3>
        <p>Enter your income from all sources:</p>
        <ul>
          <li><strong>Salary income</strong> — Use figures from your salary certificate or employer's annual summary</li>
          <li><strong>Business income</strong> — Enter total receipts and allowable business expenses</li>
          <li><strong>Rental income</strong> — Declare any income from renting property</li>
          <li><strong>Investment income</strong> — Dividends, profit on bank deposits, capital gains</li>
          <li><strong>Tax deducted at source</strong> — Enter total WHT deducted by employer or bank</li>
        </ul>

        <h3>Step 5 — Complete the Wealth Statement</h3>
        <p>
          The wealth statement is mandatory. Declare all your assets (opening and closing balance) and reconcile the difference with your declared income. Assets include property, vehicles, bank balances, investments, and personal belongings of significant value.
        </p>

        <h3>Step 6 — Claim Applicable Tax Credits</h3>
        <p>You may be entitled to reduce your tax liability through these credits:</p>
        <ul>
          <li><strong>Advance tax paid</strong> (Section 147) — adjustable against final liability</li>
          <li><strong>Education expenses</strong> — up to PKR 600,000 deductible</li>
          <li><strong>Health insurance premiums</strong> — deductible under certain conditions</li>
          <li><strong>Pension fund contributions</strong> — deductible up to 20% of income</li>
          <li><strong>Zakat paid</strong> — deductible if paid through official channels</li>
          <li><strong>Teachers and researchers</strong> — 25% reduction in income tax (if employed in a recognised institution)</li>
        </ul>

        <h3>Step 7 — Review, Submit and Pay</h3>
        <p>
          Carefully review all entries. Errors in the wealth statement or income figures are the most common cause of FBR audit notices. Once satisfied, click Submit. If you have a tax balance due, IRIS will generate a <strong>PSID (Payment Slip ID)</strong>. Pay using internet banking, ATM, or at any bank branch by quoting your PSID.
        </p>

        <h3>Step 8 — Confirm Submission</h3>
        <p>
          After submission, your return status in IRIS will change to "Completed" and you will receive a Computerised Payment Receipt (CPR) if tax was due. Your ATL status typically updates within <strong>24–72 hours</strong>.
        </p>

        <h2 id="atl-surcharge">Late Filing and the ATL Surcharge</h2>
        <p>
          The official tax return deadline for individuals and AOPs is <strong>September 30, 2026</strong> for Tax Year 2026. FBR sometimes grants extensions — check fbr.gov.pk for announcements closer to the deadline.
        </p>
        <p>
          If you file <strong>after the deadline</strong>, you are classified as a Late Filer. To appear on the ATL as a late filer, you must pay the <strong>ATL Surcharge</strong>:
        </p>
        <table>
          <thead>
            <tr><th>Taxpayer Type</th><th>ATL Surcharge Amount</th></tr>
          </thead>
          <tbody>
            <tr><td>Individual</td><td>PKR 1,000</td></tr>
            <tr><td>AOP (Association of Persons)</td><td>PKR 10,000</td></tr>
            <tr><td>Company</td><td>PKR 20,000</td></tr>
          </tbody>
        </table>
        <p>
          In addition to the ATL surcharge, late filing attracts a penalty of <strong>PKR 1,000 per day</strong> of default, with a minimum penalty of PKR 10,000 for individuals. Continued non-compliance can lead to SIM card blockage under FBR's authority with NADRA/PTA.
        </p>
        <div className="callout-warning">
          <strong>Even if your income is zero:</strong> File a nil return before the deadline. It costs nothing and prevents penalties, keeps your ATL status active, and avoids the PKR 1,000/day late filing penalty.
        </div>

        <h2 id="verify-atl">How to Verify Your ATL Status</h2>
        <p>After filing, confirm your name appears on the Active Taxpayer List using one of these methods:</p>
        <ul>
          <li><strong>SMS:</strong> Send <em>ATL [space] 13-digit CNIC</em> to <strong>9966</strong>. You will receive an instant reply confirming your status.</li>
          <li><strong>FBR Website:</strong> Go to <em>fbr.gov.pk</em> → Taxpayer Facilitation → Active Taxpayer List. Search by CNIC or NTN.</li>
          <li><strong>Tax Asaan App:</strong> Download the FBR Tax Asaan app and check your filer status directly.</li>
        </ul>
        <p>ATL status typically updates within <strong>24–72 hours</strong> of filing. If your status has not updated after 72 hours, contact the FBR helpline at <strong>0800-00-227</strong>.</p>

        <h2 id="faq">Frequently Asked Questions</h2>

        <h3>Can I become a filer if I have never paid taxes before?</h3>
        <p>
          Yes. You can file a return for previous years even if you have never paid taxes before. If you have missed multiple years, it is strongly recommended to consult a professional tax consultant to correctly prepare a wealth reconciliation covering the missing period. <Link href="/contact">Contact Akbar Tax Store</Link> for assistance.
        </p>

        <h3>Does my employer already file my return?</h3>
        <p>
          No. Your employer deducts and deposits withholding tax (WHT) on your salary — but this does not count as filing your personal income tax return. You must still file your own annual return on IRIS using your employer's salary certificate to officially become a filer.
        </p>

        <h3>What happens if I stop filing after becoming a filer?</h3>
        <p>
          If you miss three consecutive annual returns, you can be reclassified as an Inactive Taxpayer. Your name is removed from the ATL and you revert to non-filer status, facing higher withholding taxes on all transactions.
        </p>

        <h3>How do I become a filer quickly before a property purchase?</h3>
        <p>
          The fastest path is: get NTN (if you don't have one) → file current year return on IRIS → pay ATL surcharge (if late) → ATL updates within 24–72 hours. <Link href="/services/filer-status">Akbar Tax Store can complete this entire process for you within 24 hours</Link>.
        </p>

      </GuideLayout>
    </>
  );
}